
package com.u_learn.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.u_learn.ws.pojo.ObjectFactory;
import com.u_learn.ws.pojo.ViewModelResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService1", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService1 {


    /**
     * 
     * @param email
     * @return
     *     returns com.u_learn.ws.pojo.ViewModelResponse
     */
    @WebMethod(operationName = "ExistUser", action = "http://tempuri.org/IService1/ExistUser")
    @WebResult(name = "ExistUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExistUser", targetNamespace = "http://tempuri.org/", className = "com.u_learn.ws.pojo.ExistUser")
    @ResponseWrapper(localName = "ExistUserResponse", targetNamespace = "http://tempuri.org/", className = "com.u_learn.ws.pojo.ExistUserResponse")
    public ViewModelResponse existUser(
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        String email);

}
